# Generated by Django 6.1.2 on 2026-10-09 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('item_type', models.CharField(choices=[('event', 'Wydarzenie / Spotkanie'), ('task', 'Zadanie do wykonania'), ('deadline', 'Ważna data / Termin')], default='task', max_length=20)),
                ('due_date', models.DateTimeField(verbose_name='Termin / Data')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Wykonane')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planner_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
